version: "3.6"

volumes:
  db_data:
      driver: local

services:
  api:
    container_name: backend
    build: .    
    environment:
      DB_HOST: "localhost"
      DB_PORT: "3306"
      DB_USER: "labuser"
      DB_PASSWORD: "P@$$w0rd"
      DB_DATABASE: "invinsense"
    networks:
      - default
    ports:
      - 5000:5000
    depends_on:
        - mariadb
    restart: always
  mariadb:
      container_name: mariadb
      image: mariadb:latest
      volumes:
        - db_data:/var/lib/mariadb
      environment:
        MARIADB_ROOT_PASSWORD: M@r!@dbr00t
        MARIADB_DATABASE: keycloak
        MARIADB_USER: labuser
        MARIADB_PASSWORD: P@$$w0rd
      ports:
        - 3306:3306
  keycloak:
      container_name: keycloak
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: mariadb
        DB_DATABASE: keycloak
        DB_USER: labuser
        DB_PASSWORD: P@$$w0rd
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      ports:
        - 8080:8080
      depends_on:
        - mariadb
  webserver:
     container_name: nginx
     image: nginx:latest
     ports:
       - 8888:80
